make.contigs(file=malaga, deltaq=10, insert=30, trimoverlap=F, processors=20)
summary.seqs(fasta=current)
screen.seqs(fasta=current, group=current, maxambig=0, maxhomop=10, contigsreport=current)
summary.seqs(fasta=current)
screen.seqs(fasta=current, group=current, minlength=250)
summary.seqs(fasta=current)
unique.seqs(fasta=current)
summary.seqs(fasta=current, name=current)
get.current()
chimera.vsearch(fasta=current, name=current, group=current, dereplicate=f)
remove.seqs(fasta=current, accnos=current, group=current, name=current, dups=t)
summary.seqs(fasta=current, name=current)
pre.cluster(fasta=current, name=current, group=current, diffs=1, method=unoise)
count.seqs(count=current, compress=f)
